"""empty message

Revision ID: 4ac75a6b965a
Revises: 33368ea99e51
Create Date: 2021-12-27 09:22:08.133218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac75a6b965a'
down_revision = '33368ea99e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_photo_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'photo_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comments_photo_id_fkey', 'comments', 'photos', ['photo_id'], ['id'])
    # ### end Alembic commands ###
